/* =====================================================================
   BANCO DE PREGUNTAS — de aquí sale el generador de examen.
   (Preguntas basadas en los apuntes «Matemáticas aplicadas». )

   · Las preguntas se agrupan por número de módulo (1, 2, 3…), el mismo que en datos/temario.js.
   · Hay dos tipos de pregunta:

     TEST (una sola respuesta correcta, 1 punto):
       { tipo: "test",
         enunciado: "…",
         opciones: ["…", "…", "…", "…"],   // entre 3 y 5 opciones; el generador las baraja
         correcta: 1,                      // posición de la correcta en "opciones" (0 = la primera)
         explicacion: "…" }

     PROBLEMA (se resuelve a mano, 2 puntos):
       { tipo: "calculo",
         enunciado: "…",
         espacio: "m",                     // espacio para desarrollar: "s" (poco), "m" (medio) o "l" (mucho)
         solucion: ["paso 1", "paso 2"],   // resolución paso a paso (hoja de soluciones)
         respuesta: "…" }                  // resultado final

   · Fórmulas: se escriben entre signos $ … $ con una versión sencilla de LaTeX:
       fracción  \frac{3}{4}      potencia  x^2  o  x^{10}      subíndice  x_v
       raíz      \sqrt{144}       símbolos  \cdot  \times  \pi  \approx  \le  \ge  \neq  \pm
     Se usa String.raw (la "r" delante de las comillas invertidas) para no tener que duplicar las barras.

   · Si cambias o quitas preguntas, sube BANCO_VERSION: así los códigos de exámenes antiguos
     avisan de que ya no coinciden con el banco actual.
   ===================================================================== */
const r = String.raw;
const BANCO_VERSION = 3;

const PREGUNTAS = {

  /* ------------------------- Tema 1 · Porcentajes ------------------------- */
  1: [
    { tipo: "test",
      enunciado: r`Un producto cuesta 150 € sin IVA. Con un IVA del 21 %, ¿cuál es su precio final?`,
      opciones: ["171,50 €", "181,50 €", "182,50 €", "210 €"],
      correcta: 1,
      explicacion: r`Precio con IVA = precio sin IVA $\times\, 1,21$: $150\cdot 1,21=181,5$ €.` },
    { tipo: "test",
      enunciado: r`Un producto cuesta 242 € con un IVA del 21 % incluido. ¿Cuánto costaba sin IVA?`,
      opciones: ["191,18 €", "200 €", "220 €", "242 €"],
      correcta: 1,
      explicacion: r`Precio sin IVA = precio con IVA entre 1,21: $\frac{242}{1,21}=200$ €.` },
    { tipo: "test",
      enunciado: "Una trabajadora tiene un salario bruto de 2.500 €, una retención de IRPF del 15 % y una cotización a la Seguridad Social del 6 %. ¿Cuál es su sueldo neto?",
      opciones: ["1.875 €", "1.975 €", "2.125 €", "2.350 €"],
      correcta: 1,
      explicacion: r`Se descuenta el 15 % + 6 % = 21 %: $2500\cdot 0,21=525$ y $2500-525=1975$ €.` },
    { tipo: "test",
      enunciado: "Un producto de 800 € sube un 3 % por la inflación. ¿Cuál es su nuevo precio?",
      opciones: ["803 €", "824 €", "830 €", "840 €"],
      correcta: 1,
      explicacion: r`La subida es $800\cdot\frac{3}{100}=24$ €, luego el precio nuevo es $800+24=824$ €.` },
    { tipo: "test",
      enunciado: "Se vende una casa por 250.000 € y la inmobiliaria cobra una comisión del 4 %. ¿Cuánto cobra la inmobiliaria?",
      opciones: ["1.000 €", "10.000 €", "100.000 €", "240.000 €"],
      correcta: 1,
      explicacion: r`$250000\cdot\frac{4}{100}=10000$ €.` },
    { tipo: "calculo",
      enunciado: "Un producto cuesta 80 € sin IVA. Calcula el IVA (21 %) y el precio con IVA.",
      espacio: "s",
      solucion: [r`IVA: $80\cdot 0,21=16,8$ €.`, r`Precio con IVA: $80+16,8=96,8$ € (o bien $80\cdot 1,21=96,8$ €).`],
      respuesta: "IVA: 16,80 €. Precio con IVA: 96,80 €." },
    { tipo: "calculo",
      enunciado: "Un producto cuesta 121 € con un IVA del 21 % incluido. Calcula su precio sin IVA y el IVA que se paga.",
      espacio: "s",
      solucion: [r`Precio sin IVA: $\frac{121}{1,21}=100$ €.`, r`IVA: $121-100=21$ €.`],
      respuesta: "Precio sin IVA: 100 €. IVA: 21 €." },
    { tipo: "calculo",
      enunciado: "Se compra una casa valorada en 120.000 € y hay que pagar un 8 % de ITP (Impuesto de Transmisiones Patrimoniales). ¿Cuánto cuesta en total?",
      espacio: "s",
      solucion: [r`ITP: $120000\cdot\frac{8}{100}=9600$ €.`, r`Total: $120000+9600=129600$ €.`],
      respuesta: "129.600 €" },
    { tipo: "calculo",
      enunciado: "Un representante cobra una comisión del 9 % sobre 15.000 €. ¿Qué cantidad obtiene cada uno, el representante y su representado?",
      espacio: "s",
      solucion: [r`Representante: $15000\cdot\frac{9}{100}=1350$ €.`, r`Representado: $15000-1350=13650$ €.`],
      respuesta: "Representante: 1.350 €. Representado: 13.650 €." }
  ],

  /* ------------------------- Tema 2 · Cantidades iniciales y finales ------------------------- */
  2: [
    { tipo: "test",
      enunciado: "Unas acciones de 2.000 € suben un 5 %. ¿Cuánto valen después de la subida?",
      opciones: ["2.010 €", "2.050 €", "2.100 €", "2.500 €"],
      correcta: 2,
      explicacion: r`$C_f=C_i\cdot 1,05=2000\cdot 1,05=2100$ €.` },
    { tipo: "test",
      enunciado: "Un pantalón costaba 60 € y está rebajado un 20 %. ¿Cuánto cuesta ahora?",
      opciones: ["40 €", "48 €", "52 €", "58 €"],
      correcta: 1,
      explicacion: r`Una rebaja del 20 % es multiplicar por 0,8: $60\cdot 0,8=48$ €.` },
    { tipo: "test",
      enunciado: "Tras aplicar un descuento del 20 %, una chaqueta cuesta 72 €. ¿Cuánto costaba antes del descuento?",
      opciones: ["57,60 €", "86,40 €", "90 €", "92 €"],
      correcta: 2,
      explicacion: r`El descuento disminuye, y buscamos la cantidad inicial: $C_i=\frac{72}{0,8}=90$ €.` },
    { tipo: "test",
      enunciado: "Un producto de 200 € sube un 40 % y después baja un 40 %. ¿Cuál es su precio final?",
      opciones: ["140 €", "160 €", "168 €", "200 €"],
      correcta: 2,
      explicacion: r`$200\cdot 1,40\cdot 0,60=168$ €. Subir y bajar el mismo porcentaje no devuelve al precio inicial.` },
    { tipo: "test",
      enunciado: "Un producto vale ahora 115 € después de subir un 15 %. ¿Cuánto valía antes?",
      opciones: ["97,75 €", "100 €", "115 €", "130,50 €"],
      correcta: 1,
      explicacion: r`$C_i=\frac{115}{1,15}=100$ €.` },
    { tipo: "calculo",
      enunciado: "Una acción subió un 20 %, luego un 30 % y finalmente un 25 %. Si vale ahora 195 €, ¿cuánto valía antes de las subidas?",
      espacio: "m",
      solucion: [r`Se va hacia atrás dividiendo: $\frac{195}{1,25}=156$.`, r`$\frac{156}{1,30}=120$.`, r`$\frac{120}{1,20}=100$ €.`],
      respuesta: "100 €" },
    { tipo: "calculo",
      enunciado: "Un juguete subió un 25 % en Navidad y en la cuesta de enero se rebajó un 5 %. En enero cuesta 95 €. ¿Cuánto costaba antes de Navidad?",
      espacio: "m",
      solucion: [r`Antes de la rebaja: $\frac{95}{0,95}=100$ €.`, r`Antes de la subida: $\frac{100}{1,25}=80$ €.`],
      respuesta: "80 €" },
    { tipo: "calculo",
      enunciado: "Un producto de 150 € sube un 10 % y después baja un 20 %. ¿Cuál es su precio final?",
      espacio: "s",
      solucion: [r`Tras la subida: $150\cdot 1,1=165$ €.`, r`Tras la bajada: $165\cdot 0,8=132$ €.`],
      respuesta: "132 €" }
  ],

  /* ------------------------- Tema 3 · Porcentaje de un total ------------------------- */
  3: [
    { tipo: "test",
      enunciado: "De 10 horas de estudio, 4 son de matemáticas. ¿Qué porcentaje es de matemáticas?",
      opciones: ["4 %", "25 %", "40 %", "60 %"],
      correcta: 2,
      explicacion: r`$p=\frac{4}{10}\times 100=40$ %.` },
    { tipo: "test",
      enunciado: "En una biblioteca hay 800 libros y 200 son de matemáticas. ¿Qué porcentaje representan?",
      opciones: ["20 %", "25 %", "40 %", "75 %"],
      correcta: 1,
      explicacion: r`$p=\frac{200}{800}\times 100=25$ %.` },
    { tipo: "test",
      enunciado: "En un frutero hay 36 frutas y 6 son plátanos. ¿Qué porcentaje son plátanos?",
      opciones: ["6 %", "16,67 %", "18 %", "60 %"],
      correcta: 1,
      explicacion: r`$p=\frac{6}{36}\times 100=16,67$ %.` },
    { tipo: "test",
      enunciado: "En una bolsa hay 250 bolas y el 20 % son rojas. ¿Cuántas bolas rojas hay?",
      opciones: ["20", "25", "50", "200"],
      correcta: 2,
      explicacion: r`$250\cdot\frac{20}{100}=250\cdot 0,2=50$ bolas.` },
    { tipo: "test",
      enunciado: "El 15 % de las frutas de un almacén son plátanos y hay 120 plátanos. ¿Cuántas frutas hay en total?",
      opciones: ["18", "135", "800", "1.800"],
      correcta: 2,
      explicacion: r`$\frac{120}{15}=\frac{x}{100}$, luego $x=\frac{120\cdot 100}{15}=800$ frutas.` },
    { tipo: "calculo",
      enunciado: "En un almacén, el 15 % de la fruta son plátanos y hay 150 unidades de plátano. ¿Cuántas frutas hay en total?",
      espacio: "s",
      solucion: [r`$\frac{150}{15}=\frac{x}{100}$.`, r`$x=\frac{150\cdot 100}{15}=\frac{15000}{15}=1000$.`],
      respuesta: "1.000 frutas" },
    { tipo: "calculo",
      enunciado: "En una clase de 40 alumnos aprueban 34. ¿Qué porcentaje aprueba y cuántos suspenden?",
      espacio: "s",
      solucion: [r`Porcentaje de aprobados: $p=\frac{34}{40}\times 100=85$ %.`, r`Suspenden $40-34=6$ alumnos, es decir, el 15 %.`],
      respuesta: "Aprueba el 85 %; suspenden 6 alumnos." }
  ],

  /* ------------------------- Tema 4 · Variación absoluta y porcentual ------------------------- */
  4: [
    { tipo: "test",
      enunciado: "Al empezar el mes había 7.000 € en el banco y a mitad de mes hay 6.200 €. ¿Cuál es la variación absoluta?",
      opciones: ["−800 €", "−200 €", "800 €", "6.200 €"],
      correcta: 0,
      explicacion: r`$V_A=C_f-C_i=6200-7000=-800$ €.` },
    { tipo: "test",
      enunciado: "Con los datos anteriores (de 7.000 € a 6.200 €), ¿cuál es la variación porcentual?",
      opciones: ["−8 %", "−11,43 %", "−12,90 %", "11,43 %"],
      correcta: 1,
      explicacion: r`$V_P=\frac{-800}{7000}\times 100=-11,43$ %.` },
    { tipo: "test",
      enunciado: "Los ahorros de una persona pasan de 2.500 € a 2.000 €. ¿Cuál es la variación porcentual?",
      opciones: ["−500 %", "−25 %", "−20 %", "20 %"],
      correcta: 2,
      explicacion: r`$V_P=\frac{2000-2500}{2500}\times 100=\frac{-500}{2500}\times 100=-20$ %.` },
    { tipo: "test",
      enunciado: "Los camiones descargados pasan de 100.000 en 2019 a 125.000 en 2025. ¿Cuál es la variación porcentual?",
      opciones: ["20 %", "25 %", "125 %", "−25 %"],
      correcta: 1,
      explicacion: r`$V_P=\frac{125000-100000}{100000}\cdot 100=25$ %.` },
    { tipo: "test",
      enunciado: "Un autónomo ganó 2.000 € un mes y 1.800 € el siguiente. ¿Cuál es la variación porcentual?",
      opciones: ["−200 %", "−11,11 %", "−10 %", "10 %"],
      correcta: 2,
      explicacion: r`$V_P=\frac{1800-2000}{2000}\times 100=-10$ %. Se divide siempre entre la cantidad inicial.` },
    { tipo: "calculo",
      enunciado: "Los ahorros de una persona fueron 2.000 € en 2025 y 4.000 € en 2026. Calcula la variación absoluta y la variación porcentual.",
      espacio: "s",
      solucion: [r`$V_A=4000-2000=2000$ €.`, r`$V_P=\frac{4000-2000}{2000}\times 100=100$ %.`],
      respuesta: "Variación absoluta: 2.000 €. Variación porcentual: 100 %." },
    { tipo: "calculo",
      enunciado: "Un valor pasó de 1.500 en 1980 a 1.750 en 1995. Calcula la variación absoluta y la variación porcentual.",
      espacio: "s",
      solucion: [r`$V_A=1750-1500=250$.`, r`$V_P=\frac{250}{1500}\cdot 100=16,67$ %.`],
      respuesta: "Variación absoluta: 250. Variación porcentual: 16,67 %." }
  ],

  /* ------------------------- Tema 5 · Interés simple ------------------------- */
  5: [
    { tipo: "test",
      enunciado: "Se invierten 5.000 € al 3 % anual con interés simple durante 4 años. ¿Qué interés se obtiene?",
      opciones: ["150 €", "600 €", "650 €", "5.600 €"],
      correcta: 1,
      explicacion: r`Cada año: $5000\cdot\frac{3}{100}=150$ €. En 4 años: $150\cdot 4=600$ €.` },
    { tipo: "test",
      enunciado: "Si el interés es anual y el dinero está invertido 6 meses, ¿cuántos años hay que usar en la fórmula?",
      opciones: ["0,5", "0,6", "6", "12"],
      correcta: 0,
      explicacion: r`Se pasan los meses a años: $\frac{6}{12}=0,5$.` },
    { tipo: "test",
      enunciado: "A interés simple se invierten 2.500 € y se obtienen 3.200 €. ¿Qué interés se ha generado?",
      opciones: ["300 €", "700 €", "5.700 €", "3.200 €"],
      correcta: 1,
      explicacion: r`Interés $=C_f-C_i=3200-2500=700$ €.` },
    { tipo: "test",
      enunciado: "Con esos mismos datos (interés de 700 € sobre 2.500 € durante 7 años), ¿qué tasa anual se ha aplicado?",
      opciones: ["2,8 %", "4 %", "28 %", "40 %"],
      correcta: 1,
      explicacion: r`tasa $=\frac{700}{2500\cdot 7}=0,04$, es decir, un 4 %.` },
    { tipo: "test",
      enunciado: "Una inversión de 6.000 € al 1 % anual (interés simple) ha generado 500 € de interés. ¿Cuántos años han pasado?",
      opciones: ["5 años", "8,33 años", "10 años", "12 años"],
      correcta: 1,
      explicacion: r`años $=\frac{500}{6000\cdot 0,01}=8,33$, es decir, 8 años y 4 meses.` },
    { tipo: "calculo",
      enunciado: "Calcula el interés simple de un capital de 30.000 € a una tasa anual del 5 % durante 6 años, y el capital final.",
      espacio: "s",
      solucion: [r`Interés de un año: $30000\cdot\frac{5}{100}=1500$ €.`, r`En 6 años: $1500\cdot 6=9000$ €.`, r`Capital final: $30000+9000=39000$ €.`],
      respuesta: "Interés: 9.000 €. Capital final: 39.000 €." },
    { tipo: "calculo",
      enunciado: "Un interés simple durante 18 meses a un tipo anual del 2 % ha dado 200 € de interés. Calcula el capital inicial y el capital final.",
      espacio: "m",
      solucion: [r`Tiempo: $\frac{18}{12}=1,5$ años.`, r`$200=C_i\cdot 0,02\cdot 1,5=C_i\cdot 0,03$, luego $C_i=\frac{200}{0,03}\approx 6666,67$ €.`, r`$C_f=6666,67+200=6866,67$ €.`],
      respuesta: "Capital inicial: 6.666,67 €. Capital final: 6.866,67 €." }
  ],

  /* ------------------------- Tema 6 · Interés compuesto ------------------------- */
  6: [
    { tipo: "test",
      enunciado: "¿Cuál es la fórmula del capital final con interés compuesto?",
      opciones: [r`$C_f=C_i\cdot(1+t)^n$`, r`$C_f=C_i\cdot(1+t\cdot n)$`, r`$C_f=C_i+t\cdot n$`, r`$C_f=C_i\cdot t^n$`],
      correcta: 0,
      explicacion: r`Los intereses se reinvierten, por eso el factor $(1+t)$ se multiplica una vez por cada año ($t$ es la tasa en tanto por uno y $n$ el número de años).` },
    { tipo: "test",
      enunciado: "Se invierten 1.000 € al 5 % anual con interés compuesto durante 3 años. ¿Cuál es el capital final?",
      opciones: ["1.105 €", "1.150 €", "1.157,63 €", "1.200 €"],
      correcta: 2,
      explicacion: r`$1000\cdot 1,05^3=1157,625\approx 1157,63$ €. Con interés simple serían 1.150 €.` },
    { tipo: "test",
      enunciado: "Se invierten 2.000 € al 4 % anual con interés compuesto durante 2 años. ¿Cuál es el capital final?",
      opciones: ["2.160 €", "2.163,20 €", "2.166,40 €", "2.200 €"],
      correcta: 1,
      explicacion: r`$2000\cdot 1,04^2=2163,2$ €.` },
    { tipo: "test",
      enunciado: "Se invierten 4.000 € al 5 % durante 2 años con interés compuesto. ¿Cuál es el capital final?",
      opciones: ["4.200 €", "4.400 €", "4.410 €", "4.500 €"],
      correcta: 2,
      explicacion: r`$4000\cdot 1,05^2=4410$ €.` },
    { tipo: "test",
      enunciado: "Una acción de 120 € se incrementa un 5 % cada año durante 3 años. ¿Cuánto vale al final?",
      opciones: ["135 €", "138 €", "138,92 €", "141,50 €"],
      correcta: 2,
      explicacion: r`$120\cdot 1,05^3=138,915\approx 138,92$ €.` },
    { tipo: "calculo",
      enunciado: "La inflación de un producto de estética es del 5 % un año y del 4 % el siguiente. ¿Qué precio se puede esperar si al principio valía 30 €?",
      espacio: "s",
      solucion: [r`Primer año: $30\cdot 1,05=31,5$ €.`, r`Segundo año: $31,5\cdot 1,04=32,76$ €.`],
      respuesta: "32,76 €" },
    { tipo: "calculo",
      enunciado: "Una empresa tenía 2.500 clientes. En un año aumentaron un 12 % y al año siguiente un 8 %. ¿Cuántos clientes tiene finalmente?",
      espacio: "m",
      solucion: [r`Primer año: $2500\cdot 1,12=2800$ clientes.`, r`Segundo año: $2800\cdot 1,08=3024$ clientes.`],
      respuesta: "3.024 clientes" },
    { tipo: "calculo",
      enunciado: "Se invierten 5.000 € al 3 % anual con interés compuesto durante 2 años. Calcula el capital final y el interés acumulado.",
      espacio: "s",
      solucion: [r`$C_f=5000\cdot 1,03^2=5304,5$ €.`, r`Interés acumulado: $5304,5-5000=304,5$ €.`],
      respuesta: "Capital final: 5.304,50 €. Interés acumulado: 304,50 €." }
  ],

  /* ------------------------- Tema 7 · Proporcionalidad ------------------------- */
  7: [
    { tipo: "test",
      enunciado: "Si 3 azucarillos tienen 21 gramos de azúcar, ¿cuántos gramos tienen 5 azucarillos?",
      opciones: ["30 g", "35 g", "42 g", "63 g"],
      correcta: 1,
      explicacion: r`Regla de tres: $x=\frac{21\cdot 5}{3}=35$ g.` },
    { tipo: "test",
      enunciado: "En una proporcionalidad, cuando una variable aumenta la otra disminuye y el producto de las dos es constante. ¿De qué tipo es?",
      opciones: ["Directa", "Inversa", "Numérica", "No es proporcionalidad"],
      correcta: 1,
      explicacion: r`En la proporcionalidad inversa se multiplica y el producto es constante: $k=x\cdot y$. En la directa se divide: $k=\frac{y}{x}$.` },
    { tipo: "test",
      enunciado: "Dos personas recogen la mesa de una fiesta en 30 minutos. ¿Cuánto tardarían 5 personas?",
      opciones: ["12 minutos", "20 minutos", "45 minutos", "75 minutos"],
      correcta: 0,
      explicacion: r`Es inversa: $2\cdot 30=5\cdot x$, luego $x=\frac{60}{5}=12$ minutos.` },
    { tipo: "test",
      enunciado: "Imprimir 1 libro necesita 300 folios, 2 libros 600 folios y 3 libros 900 folios. ¿Cuál es la constante de proporcionalidad?",
      opciones: ["3", "30", "300", "900"],
      correcta: 2,
      explicacion: r`Es directa: $k=\frac{y}{x}=\frac{600}{2}=300$ folios por libro.` },
    { tipo: "test",
      enunciado: "A 80 km/h se tarda 3 horas en hacer un trayecto. ¿Cuánto se tardaría a 60 km/h?",
      opciones: ["2 horas", "3 horas", "4 horas", "5 horas"],
      correcta: 2,
      explicacion: r`Es inversa: $80\cdot 3=240$, luego $60\cdot x=240$ y $x=4$ horas.` },
    { tipo: "calculo",
      enunciado: "Un coche gasta 2,5 litros de gasolina cada 50 km. ¿Cuántos litros gastará en 400 km?",
      espacio: "s",
      solucion: [r`Es directa: $\frac{50}{2,5}=\frac{400}{x}$.`, r`$x=\frac{2,5\cdot 400}{50}=20$ litros.`],
      respuesta: "20 litros" },
    { tipo: "calculo",
      enunciado: "Calcula $x$ en la proporción $\frac{4}{7}=\frac{8}{x}$.",
      espacio: "s",
      solucion: [r`Se multiplica en cruz: $4x=7\cdot 8=56$.`, r`$x=\frac{56}{4}=14$.`],
      respuesta: r`$x=14$` },
    { tipo: "calculo",
      enunciado: "6 obreros terminan una obra en 10 días. ¿Cuántos días tardarían 15 obreros trabajando al mismo ritmo?",
      espacio: "s",
      solucion: [r`Es inversa: $6\cdot 10=15\cdot x$.`, r`$x=\frac{60}{15}=4$ días.`],
      respuesta: "4 días" },
    { tipo: "test",
      enunciado: "Una tabla tiene los valores 2, 4, 8 y 10 en la primera fila y 100, 50, 10 y 2 en la segunda. \u00bfEs una proporcionalidad inversa?",
      opciones: ["S\u00ed: todos los productos valen 200", "No: los productos son 200, 200, 80 y 20", "S\u00ed: una variable sube y la otra baja", "No: es una proporcionalidad directa"],
      correcta: 1,
      explicacion: r`En la inversa el producto debe ser constante: $2\cdot 100=200$, $4\cdot 50=200$, pero $8\cdot 10=80$ y $10\cdot 2=20$.` },
    { tipo: "calculo",
      enunciado: "Un saco de arroz pesa 45 kg y en cada kilo hay 5 gramos de arroz en mal estado. \u00bfCu\u00e1ntos gramos en mal estado habr\u00e1 en 3 sacos?",
      espacio: "s",
      solucion: [r`Peso total: $45\cdot 3=135$ kg.`, r`Arroz en mal estado: $135\cdot 5=675$ g.`],
      respuesta: "675 g" }
  ],

  /* ------------------------- Tema 8 · Despejar incógnitas ------------------------- */
  8: [
    { tipo: "test",
      enunciado: r`Despeja $V$ en la fórmula $E=V\cdot t$.`,
      opciones: [r`$V=E\cdot t$`, r`$V=\frac{E}{t}$`, r`$V=\frac{t}{E}$`, r`$V=E-t$`],
      correcta: 1,
      explicacion: r`Como $V$ multiplica a $t$, $t$ pasa dividiendo: $V=\frac{E}{t}$.` },
    { tipo: "test",
      enunciado: r`Despeja $V$ en la fórmula $I=\frac{V}{R}$.`,
      opciones: [r`$V=\frac{I}{R}$`, r`$V=\frac{R}{I}$`, r`$V=I\cdot R$`, r`$V=I-R$`],
      correcta: 2,
      explicacion: r`Como $R$ divide a $V$, $R$ pasa multiplicando: $V=I\cdot R$.` },
    { tipo: "test",
      enunciado: r`Resuelve la ecuación $3x+1=4$.`,
      opciones: [r`$x=\frac{5}{3}$`, r`$x=1$`, r`$x=3$`, r`$x=\frac{4}{3}$`],
      correcta: 1,
      explicacion: r`$3x=4-1=3$, luego $x=\frac{3}{3}=1$.` },
    { tipo: "test",
      enunciado: "En el interés simple, ¿cómo se calcula la tasa a partir del interés, el capital inicial y los años?",
      opciones: [r`$\text{tasa}=\text{Interés}\cdot C_i\cdot\text{años}$`, r`$\text{tasa}=\frac{\text{Interés}}{C_i\cdot\text{años}}$`, r`$\text{tasa}=\frac{C_i\cdot\text{años}}{\text{Interés}}$`, r`$\text{tasa}=\frac{\text{Interés}}{C_i}+\text{años}$`],
      correcta: 1,
      explicacion: r`De $\text{Interés}=C_i\cdot\text{tasa}\cdot\text{años}$ se despeja dividiendo entre $C_i\cdot\text{años}$.` },
    { tipo: "calculo",
      enunciado: r`Resuelve la ecuación $5x-2=13$.`,
      espacio: "s",
      solucion: [r`$5x=13+2=15$.`, r`$x=\frac{15}{5}=3$.`],
      respuesta: r`$x=3$` }
  ],

  /* ------------------------- Tema 9 · Tablas y frecuencias ------------------------- */
  9: [
    { tipo: "test",
      enunciado: "¿Qué es la frecuencia absoluta de un dato?",
      opciones: ["El número de veces que aparece", "El porcentaje que representa", "El cociente entre el dato y la media", "La suma de todos los datos"],
      correcta: 0,
      explicacion: "La frecuencia absoluta (FA) es el número de apariciones del dato." },
    { tipo: "test",
      enunciado: "En un grupo de 40 personas, 12 prefieren el fútbol. ¿Cuál es la frecuencia relativa del fútbol?",
      opciones: ["0,12", "0,3", "3", "30"],
      correcta: 1,
      explicacion: r`$FR=\frac{FA}{\text{total}}=\frac{12}{40}=0,3$, que equivale a un 30 %.` },
    { tipo: "test",
      enunciado: "¿Cuánto suman todas las frecuencias relativas de una tabla?",
      opciones: ["0", "1", "100", "El número de datos"],
      correcta: 1,
      explicacion: r`$\sum fr_i=1$. Los porcentajes, en cambio, suman 100 %.` },
    { tipo: "test",
      enunciado: "En una clase de 20 alumnos, 4 sacaron un 5. ¿Qué porcentaje representa?",
      opciones: ["4 %", "5 %", "20 %", "25 %"],
      correcta: 2,
      explicacion: r`$FR=\frac{4}{20}=0,2$ y $0,2\times 100=20$ %.` },
    { tipo: "calculo",
      enunciado: "En un grupo de 50 personas, 20 prefieren fútbol, 15 baloncesto, 10 natación y 5 tenis. Calcula la frecuencia relativa y el porcentaje de cada deporte.",
      espacio: "l",
      solucion: [r`Fútbol: $\frac{20}{50}=0,4$ (40 %).`, r`Baloncesto: $\frac{15}{50}=0,3$ (30 %).`, r`Natación: $\frac{10}{50}=0,2$ (20 %).`, r`Tenis: $\frac{5}{50}=0,1$ (10 %). Las frecuencias relativas suman 1 y los porcentajes 100 %.`],
      respuesta: "Fútbol 0,4 (40 %), baloncesto 0,3 (30 %), natación 0,2 (20 %) y tenis 0,1 (10 %)." }
  ],

  /* ------------------------- Tema 10 · Representaciones gráficas ------------------------- */
  10: [
    { tipo: "test",
      enunciado: "¿Qué gráfica es la más adecuada para mostrar la evolución de una cantidad a lo largo del tiempo?",
      opciones: ["Gráfica de barras", "Gráfica de sectores", "Gráfica de líneas", "Tabla de frecuencias"],
      correcta: 2,
      explicacion: "La gráfica de líneas se usa para ver cómo evoluciona una magnitud con el tiempo." },
    { tipo: "test",
      enunciado: "¿Qué gráfica representa partes de un total que han de sumar el 100 %?",
      opciones: ["Gráfica de líneas", "Gráfica de barras", "Gráfica de sectores", "Ninguna de ellas"],
      correcta: 2,
      explicacion: "En la gráfica de sectores (circular) cada parte ocupa un trozo del círculo y todas suman el 100 %." },
    { tipo: "test",
      enunciado: "En un gráfico de sectores hay 5 coches negros, 10 blancos y 5 verdes. ¿Qué porcentaje del círculo ocupan los blancos?",
      opciones: ["25 %", "33,33 %", "50 %", "10 %"],
      correcta: 2,
      explicacion: r`Total: $5+10+5=20$ coches y $\frac{10}{20}=50$ %.` },
    { tipo: "test",
      enunciado: "En un aparcamiento hay 7 SEAT, 4 Mercedes, 1 BMW y 5 coches de otras marcas. ¿Qué porcentaje son SEAT?",
      opciones: ["7 %", "41,18 %", "50 %", "58,82 %"],
      correcta: 1,
      explicacion: r`Total: $7+4+1+5=17$ y $\frac{7}{17}\cdot 100=41,18$ %.` },
    { tipo: "test",
      enunciado: "En una gráfica de sectores, un sector ocupa 1/4 del círculo. ¿Qué porcentaje representa?",
      opciones: ["4 %", "14 %", "25 %", "40 %"],
      correcta: 2,
      explicacion: r`$\frac{1}{4}\cdot 100=25$ %.` },
    { tipo: "calculo",
      enunciado: "En una encuesta sobre comidas favoritas, 8 personas eligen macarrones, 10 cocido, 5 lubina, 7 pisto y 12 otra. ¿Cuántas personas han respondido? ¿Qué porcentaje eligió cocido? ¿Cuántas eligieron algo distinto al cocido?",
      espacio: "m",
      solucion: [r`Total: $8+10+5+7+12=42$ personas.`, r`Cocido: $\frac{10}{42}\cdot 100\approx 23,81$ %.`, r`Distinto al cocido: $42-10=32$ personas.`],
      respuesta: "42 personas; el 23,81 % eligió cocido; 32 personas eligieron otra cosa." }
  ]
};
